name = "Nuclear Family Edition"
author = "Team Core"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c7876ebe4d71ec3a1d78bcf1005d4837411200342f49f0e18807693f1274ed3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
