name = "Nuclear Family Edition"
author = "Team Core"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8068c9a108f9b12461abe94dcf5043b590352e883fa8e98dc1d1de3c996ca716"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
