name = "Nuclear Family Edition"
author = "Team Core"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "143b29f82b7447046b6e1739ac6af47e3de6e797f7d2737fdd56d75a5a287410"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
